Test JRuby 9.4 and fix compatibility
Seems like referencing StringIO directly no longer works.

```
ext/java/org/msgpack/jruby/Unpacker.java:337: error: cannot find symbol
    if (stream instanceof StringIO) {
```
While I was at it I also fixed most compilation warnings.